amount_money = input('The amount of money I have is ')
price_apple = input('What is the price of the apple? ')
maximum_apples = float(amount_money) / float(price_apple)
remaining_money = float(amount_money) - float(maximum_apples * float(price_apple))
print(f"You can buy {maximum_apples} apples and your change is {remaining_money} pesos.")